name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install backend dependencies
        run: npm install
      - name: Install frontend dependencies
        run: npm install --prefix frontend
      - name: Check style
        run: npm run lint
      - name: Run backend tests
        run: npm test
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
          PORT: ${{ secrets.PORT }}
      - name: Run npm build
        run: npm run build --prefix frontend
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          SECRET: ${{ secrets.SECRET }}
          PORT: ${{ secrets.PORT }}
  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
  notify_failure:
    needs: [build_and_test, deploy]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: actions/checkout@v6
      - name: Send Failure Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: 'Build Failed! The pipeline encountered an error'
          description: |
            **Repository:** ${{ github.repository }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}
            **Workflow:** ${{ github.workflow }}
            **Job:** ${{ github.job }}
          color: 0xFF0000
  notify_success:
    needs: [deploy]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v6
      - name: Send Success Notification
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK}}
          title: 'Deployment Successful! A new version deployed to production'
          description: |
            **Commit:** ${{ github.sha }}
            **Message:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.actor }}
          color: 0x00FF00
  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ','), '#skip') }}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
